export const menuItems = [
  {
    id: "1",
    name: "Birria Taco",
    description: "",
    price: 5.99,
    imageUrl: "/menu/birria-taco.png",
    isFavorite: false,
  },
  {
    id: "2",
    name: "Quesabirria",
    description: "",
    price: 5.99,
    imageUrl: "/menu/quesabirria.png",
    isFavorite: true,
  },
  {
    id: "3",
    name: "Quesabirria Plate",
    description: "",
    price: 18.99,
    imageUrl: "/menu/quesabirria-plate.png",
    isFavorite: true,
  },
  {
    id: "4",
    name: "Grand Slam Plate",
    description: "",
    price: 18.99,
    imageUrl: "/menu/grand-slam-plate.png",
    isFavorite: true,
  },
  {
    id: "5",
    name: "Asada Tacos Plate",
    description: "",
    price: 15.99,
    imageUrl: "/menu/asada-tacos-plate.png",
    isFavorite: false,
  },
  {
    id: "6",
    name: "Mulita",
    description: "",
    price: 5.99,
    imageUrl: "/menu/mulita.png",
    isFavorite: false,
  },
  {
    id: "7",
    name: "Birria Tostada",
    description: "",
    price: 4.5,
    imageUrl: "/menu/birria-tostada.png",
    isFavorite: false,
  },
  {
    id: "8",
    name: "Birria Ramen Bowl",
    description: "",
    price: 5.99,
    imageUrl: "/menu/birria-ramen-bowl.png",
    isFavorite: false,
  },
  {
    id: "9",
    name: "Carne Asada Taco",
    description: "",
    price: 4.5,
    imageUrl: "/menu/carne-asada-taco.png",
    isFavorite: false,
  },
  {
    id: "10",
    name: "Carne Asada Quesadilla",
    description: "",
    price: 8.99,
    imageUrl: "/menu/carne-asada-quesadilla.png",
    isFavorite: false,
  },
];
